// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tarea2_ArquiSistemas.Src.Data;

#nullable disable

namespace Tarea2_ArquiSistemas.Src.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241120201036_user_db")]
    partial class user_db
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Tarea2_ArquiSistemas.Src.Models.User", b =>
                {
                    b.Property<string>("UUID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Contrasenia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorreoElectrónico")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UUID");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
